### ISSUE TITLE
想请问您，如果使用您的inference_head_masking模型进行自定义文本的摘要生成呢？

### ISSUE THREAD

**Issue by LIN-DN** [ShuyangCao/inference_head_masking#1]
看到您针对两个数据集直接提供了训练好的bart模型，并且对已经预处理好的测试集进行了一系列解码操作生成了测试集摘要并进行了评分。但是我现在想使用您的模型，应用在我的英文文本（txt）数据集上，但是不清楚如何进行对单个txt文本进行生成摘要？

**Comment by ShuyangCao** [comment]
你需要把数据处理成fairseq的格式，具体可以参照Fairseq BART的代码。如果你的数量足以训练新的sequence tagger，可以参考并修改[train_sequence_tagger_cnndm.sh](https://github.com/ShuyangCao/inference_head_masking/blob/main/scripts/train_sequence_tagger_cnndm.sh)来训练。剩下的就是一样的了。Fairseq的使用确实有点难以上手。

**Comment by LIN-DN** [comment]
您提到的test.source-target.fragment文件是在train_sequence_tagger阶段生成的吗？还是参考fairseq官方使用Roberta模型生成的呀？
